### ISSUE TITLE
EGSG airfield (Stapleford) comes up as not found when using `/station`

### ISSUE THREAD

**Issue by SimPilotAdamT** [oceanroleplay/aviationx#1]
Basically what the title says.

**Comment by vijayymmeena** [comment]
![image](https://user-images.githubusercontent.com/43092101/132487689-b9a116fb-8a1f-479f-8099-8e86c884f1d0.png)
![image](https://user-images.githubusercontent.com/43092101/132488067-ee33a91b-ec07-40ad-886e-1cd0abce4dfd.png)

aviationweather and others related services does not have any data from EGSG, maybe it become nonoperational. Please confirm, that given ICAO code is operational and data are receiving. I have attached some useful screenshot, nearest ICAO codes are EGSL and EGSS.

**Comment by vijayymmeena** [comment]
EGSG is also not registered with aviationweather.gov
