### ISSUE TITLE
WXXX Invalid

### ISSUE THREAD

**Issue by Justingaming303** [oceanroleplay/aviationx#3]
A lot of W*** ICAO airports are not found in the bot

**Comment by vijayymmeena** [comment]
Hi, I am not sure what you are asking. Bot can show information for WSSS, and I am not sure, WXXX is a valid ICAO code.

The bot gets data from aviationweather.gov, so if they have not listed a ICAO code, it won't be available.

**Comment by vijayymmeena** [comment]
If there is more to discuss, please let me know. Closing this issue for now.
